NET/TotalCoin/TotalCoin.Web/Controllers/FanpageController.cs
using Microsoft.Azure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TotalCoin.ConfigurationManager;
using TotalCoin.Entidades.Facebook;
using TotalCoin.ILogica;
using TotalCoin.Logica;
using TotalCoin.Web.Models;

namespace TotalCoin.Web.Controllers
{
    public class FanpageController : Controller
    {
        private IFanpageLogica _fanpageLogica;

        #region Constructores

        public FanpageController(IFanpageLogica fanpageLogica)
        {
            _fanpageLogica = fanpageLogica;
        }

        public FanpageController()
            : this(new FanpageLogica())
        {
        }

        #endregion Constructores

        #region Actions

        public ActionResult Index(FacebookCredentialsModel fbModel)
        {
            try
            {
                if (fbModel != null && Session["TiendaId"] != null)
                {
                    Session["FBToken"] = fbModel.AccessToken;
                    Session["SignedRequest"] = fbModel.SignedRequest;
                    Session["UserId"] = fbModel.UserId;

                    var fanpages = _fanpageLogica.GetByAccessToken(fbModel.AccessToken, CloudConfigurationManager.GetSetting(ConfigurationNames.FacebookAppId));

                    var model = new AdministrarFanpagesModel();
                    model.Fanpages = ToModel(fanpages);
                    model.NuevaTienda = fbModel.NuevaTienda;

                    return View(model);
                }
                else
                    return RedirectToAction("Index", "Tienda");
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }
        }

        public ActionResult Actualizar(FacebookCredentialsModel fbModel)
        {
            try
            {
                if (fbModel != null && Session["TiendaId"] != null)
                {
                    Session["FBToken"] = fbModel.AccessToken;
                    Session["SignedRequest"] = fbModel.SignedRequest;
                    Session["UserId"] = fbModel.UserId;

                    _fanpageLogica.ActualizarFanpages(fbModel.AccessToken, CloudConfigurationManager.GetSetting(ConfigurationNames.FacebookAppId), Convert.ToInt32(Session["TiendaId"].ToString()));

                    return RedirectToAction("Administrar", "Tienda");
                }
                else
                    return RedirectToAction("Index", "Tienda");
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }
        }

        public ActionResult Guardar(IList<FanpageModel> Fanpages)
        {
            try
            {
                if (Fanpages != null && Session["TiendaId"] != null)
                {
                    var fanpages = ToEntity(Fanpages);

                    _fanpageLogica.Guardar(fanpages, CloudConfigurationManager.GetSetting(ConfigurationNames.FacebookAppId), Convert.ToInt32(Session["TiendaId"].ToString()));
                }

                return RedirectToAction("Administrar", "Tienda", new { id = Session["TiendaId"].ToString() });
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }
        }

        public ActionResult Login(bool nuevaTienda = false) {
            return View(new AdministrarFanpagesModel() { NuevaTienda = nuevaTienda }); 
        }

        #endregion Actions

        #region Metodos privados

        private IList<FanpageModel> ToModel(IList<Fanpage> fanpages)
        {
            return fanpages.Select(fp => new FanpageModel(fp)).ToList();
        }

        private IList<Fanpage> ToEntity(IList<FanpageModel> fanpages)
        {
            return fanpages.Select(f => new Fanpage(f.Id, f.Nombre, f.Integrada, f.PageToken)).ToList();
        }

        #endregion Metodos privados
    }
}

NET/TotalCoin/TotalCoin.Web/Controllers/ProductoController.cs
using Microsoft.Azure;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TotalCoin.ConfigurationManager;
using TotalCoin.Entidades;
using TotalCoin.ILogica;
using TotalCoin.Logica;
using TotalCoin.Web.Models;

namespace TotalCoin.Web.Controllers
{
    public class ProductoController : Controller
    {
        private IProductoLogica _productoLogica;
        private ICategoriaLogica _categoriaLogica;
        private IFormaDePagoLogica _formaDePagoLogica;

        #region Constructores

        public ProductoController(IProductoLogica productoLogica, ICategoriaLogica categoriaLogica, IFormaDePagoLogica formaDePagoLogica)
        {
            _productoLogica = productoLogica;
            _categoriaLogica = categoriaLogica;
            _formaDePagoLogica = formaDePagoLogica;
        }

        public ProductoController()
            : this(new ProductoLogica(), new CategoriaLogica(), new FormaDePagoLogica())
        {
        }

        #endregion Constructores

        #region Actions

        public ActionResult Index(ListarProductosModel model)
        {
            try
            {
                var productos = new List<Producto>();

                if (Session["TiendaId"] != null)
                {
                    int tiendaId = Convert.ToInt32(Session["TiendaId"]);
                    productos = _productoLogica.GetByTienda(tiendaId).ToList();

                    foreach (Producto prod in productos)
                    {
                        prod.Category.Subcategories = _categoriaLogica.GetAllSubcategorias(prod.Category.Id).ToList();
                    }

                    var cantProductos = 5;
                    int.TryParse(CloudConfigurationManager.GetSetting(ConfigurationNames.CantidadDeProductosPorPaginaEnAdmin), out cantProductos);
                    
                    model.Productos = ToModel(_productoLogica.GetPaginado(tiendaId, 1, cantProductos).ToList());
                    model.Categorias = ToModel(_categoriaLogica.GetAllCategorias());
                    model.TiendaId = tiendaId;
                    model.Pagina = 1;
                    model.CantPaginas = _productoLogica.GetCantidadDePaginas(tiendaId, cantProductos);

                    return View(model);
                }
                else
                    return RedirectToAction("Index", "Tienda");
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }
        }

        public ActionResult GuardarProducto(ProductoModel model)
        {
            try
            {
                if (Session["TiendaId"] != null)
                {
                    int tiendaId = Convert.ToInt32(Session["TiendaId"]);

                    model.TiendaId = tiendaId;
                    var producto = ToEntidad(model);

                    producto = _productoLogica.Guardar(producto);

                    model = new ProductoModel(producto);

                    return Json(new { success = true, idProductoInsertado = model.Id });
                }
                else
                    return RedirectToAction("Index", "Tienda");
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = e.Message });
            }
        }

        public ActionResult GetCategoriasYFormasDePago()
        {
            try
            {
                var categorias = ToModel(_categoriaLogica.GetAllCategorias());
                var formasDePago = ToModel(_formaDePagoLogica.GetAll());

                return Json(new { categorias = categorias, formasDePago = formasDePago }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = e.Message });
            }
        }


        public ActionResult GetCategoriasConProductos()
        {
            try
            {
                var productos = new List<Producto>();
                var categorias = new List<Categoria>();

                if (Session["TiendaIdDesdeFB"] != null)
                {
                    int tiendaId = Convert.ToInt32(Session["TiendaIdDesdeFB"]);
                    productos = _productoLogica.GetByTienda(tiendaId).ToList();

                    foreach (Producto prod in productos)
                    {
                        //Si aun no la agregué, la agrego
                        if (categorias.Count(x => x.Id == prod.Category.Id) == 0)
                        {
                            prod.Category.Subcategories.Clear();
                            prod.Category.Subcategories.Add(prod.Subcategory);
                            categorias.Add(prod.Category);
                        } 
                        else
                        {
                            //No agrego la categoria, pero me fijo si esa subcategoria ya la habia agregado. 
                            int pos = categorias.FindIndex(x => x.Id == prod.Category.Id);
                            if(categorias[pos].Subcategories.Count(x => x.Id == prod.Subcategory.Id) == 0) {
                                //Si no tenia la categoria, la agrego
                                categorias[pos].Subcategories.Add(prod.Subcategory);
                            }
                        }
                    }

                    //Ordeno las subcategorias de cada categoria por orden alfabetico
                    foreach (Categoria categ in categorias)
                    {
                        categ.Subcategories = categ.Subcategories.OrderBy(x => x.Name).ToList();
                    }
                }
                return Json(new { categorias = ToModel(categorias.OrderBy(x => x.Name).ToList()) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = e.Message });
            }
        }

        public ActionResult GetProductos(int? pagina, string busqueda)
        {
            try
            {
                var cantProductos = 5;
                int.TryParse(CloudConfigurationManager.GetSetting(ConfigurationNames.CantidadDeProductosPorPaginaEnAdmin), out cantProductos);
                if (Session["TiendaId"] == null)
                    throw new ValidationException("Tienda invalida, por favor refresque la pagina.");

                var tiendaId = Convert.ToInt32(Session["TiendaId"].ToString());

                if (!pagina.HasValue)
                    pagina = 1;

                var productos = ToModel(_productoLogica.GetPaginado(tiendaId, pagina.Value, cantProductos, busqueda, null));
                var cantPaginas = _productoLogica.GetCantidadDePaginas(tiendaId, cantProductos, busqueda, null);

                return Json(new { success = true, productos = productos, paginaActual = pagina.Value, cantidadPaginas = cantPaginas }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e)
            {
                return Json(new { success = false, Message = e.Message }, JsonRequestBehavior.AllowGet);
            }

        }

        public ActionResult EliminarProducto(int id)
        {
            try
            {
                _productoLogica.Eliminar(id);

                return Json(new { success = true });
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = e.Message });
            }
        }

        public ActionResult GuardarImagen()
        {
            bool guardada = true;
            string fName = "";
            try
            {
                foreach (string fileName in Request.Files)
                {
                    HttpPostedFileBase imagen = Request.Files[fileName];
                    if (imagen != null && imagen.ContentLength > 0)
                        fName = GuardarImagen(imagen);
                }
            }
            catch (Exception)
            {
                guardada = false;
            }

            if (guardada)
                return Json(new { success = true, Imagen = fName });

            return Json(new { success = false, Message = "Error al guardar la imagen" });
        }

        public ActionResult Detalle(int? id, string fanpageId = "0", bool enTienda = false)
        {
            try
            {
                if (id.HasValue)
                {
                    var producto = _productoLogica.GetById(id.Value);
                    ProductoModel productoModel = ToModel(producto);
                    productoModel.AppID = CloudConfigurationManager.GetSetting(ConfigurationNames.FacebookAppId);
                    productoModel.fanpageId = fanpageId;
                    productoModel.EnTienda = enTienda;
                        
                    if (!producto.Deleted)
                    {
                        if (productoModel.Imagenes.Count == 0)
                        {
                            productoModel.Imagenes.Add("");
                        }
                        return View("DetalleProducto", productoModel);
                    }
                    else 
                    {
                        return View("Eliminado", productoModel);
                    }
                }
                else 
                {
                    //Canvase root app
                    return View("../External/AplicacionRoot");
                }
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }
        }

        public ActionResult Comprar(int productoId, int cantidad)
        {
            try
            {
                var producto = _productoLogica.GetById(productoId);

                var redirectUrl = _productoLogica.GenerarPedido(producto, cantidad);

NET/TotalCoin/TotalCoin.Web/Views/Fanpage/Index.cshtml
@model TotalCoin.Web.Models.AdministrarFanpagesModel
@{
    ViewBag.Title = "ListarFanpages";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@section Head{
    <script type="text/javascript" src="https://az653149.vo.msecnd.net/static/totalcoinstore/js/bootstrap-switch.min.js"></script>
    <link rel="stylesheet" href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/bootstrap-switch.css")">

    <script>
        $(function () {
            $("[class='my-checkbox']").bootstrapSwitch({
                size: "mini"
            });
        });

            
    </script>

}

@section Body{

    @if (Model.NuevaTienda)
    {
        <section class="">
            <div class="container">
                <div class="row bs-wizard" style="border-bottom:0;">
                    <!--
                    ESTADOS DE LOS PASOS:
                     - active
                     - disable
                     - complete
                    -->

                    <div class="col-xs-4 bs-wizard-step complete">
                        <div class="text-center bs-wizard-stepnum">Cre&aacute; tu tienda</div>
                        <div class="progress"><div class="progress-bar"></div></div>
                        <a href="#" class="bs-wizard-dot"></a>
                    </div>

                    <div class="col-xs-4 bs-wizard-step complete">
                        <!-- complete -->
                        <div class="text-center bs-wizard-stepnum">Agreg&aacute; tus productos</div>
                        <div class="progress"><div class="progress-bar"></div></div>
                        <a href="#" class="bs-wizard-dot"></a>
                    </div>

                    <div class="col-xs-4 bs-wizard-step active">
                        <!-- complete -->
                        <div class="text-center bs-wizard-stepnum">Vincul&aacute; tu tienda</div>
                        <div class="progress"><div class="progress-bar"></div></div>
                        <a href="#" class="bs-wizard-dot"></a>
                    </div>
                </div>
            </div>
        </section> <!-- end our-work-container -->
    }
    <section>
        <div class="container">
            <div class="row" style="">
                <div class="col-sm-12">
                    <h1 class="Titulo">Integr&aacute; tu tienda con tus fanpages</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h3 class="panel-title">Tus Fanpages</h3>
                        </div>
                        @using (Html.BeginForm("Guardar", "Fanpage", FormMethod.Post, new { id = "form" }))
                        {
                            <table class="table table-striped" id="dev-table">
                                <thead>
                                    <tr>
                                        <th>Nombre</th>
                                        <th>Acciones</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @for (var i = 0; i < Model.Fanpages.Count; i++)
                                    {
                                        <tr>
                                            <td>
                                                @Model.Fanpages[i].Nombre
                                            <td>
                                                @Html.HiddenFor(m => m.Fanpages[i].Id)
                                                @Html.HiddenFor(m => m.Fanpages[i].Nombre)
                                                @Html.HiddenFor(m => m.Fanpages[i].PageToken)
                                                @Html.CheckBoxFor(m => m.Fanpages[i].Integrada, new { @class = "my-checkbox" })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                    </div>
					<nav id="nav"><div class="text-center"><ul class="pagination pagination-sm"></ul></div></nav>
                </div>
            </div>
            <div class="row" style="margin-top:40px">
                <div class="col-sm-12">
                    <a href="@(Model.NuevaTienda ? Url.Action("Index", "Producto") : Url.Action("Administrar", "Tienda"))" class="btn btn-default pull-left bot">VOLVER</a>
                    <a href="#" onclick="$('#form').submit()" class="btn btn-primary pull-right bot">FINALIZAR</a>
                </div>
            </div>
        </div>
    </section>
	<script>
        $(document).ready(function(){
            // $('#dev-table').after('');
            paginate();


            function paginate() {
                var rowsShown = 4;
                var rowsTotal = $('#dev-table tbody tr').length;
                var numPages = rowsTotal / rowsShown;
                $('#nav .pagination').html("");
                for (i = 0; i < numPages; i++) {
                    var pageNum = i + 1;
                    $('#nav .pagination').append('<li><a href="#" rel="' + i + '">' + pageNum + '</a></li>');
                }
                $('#dev-table tbody tr').hide();
                $('#dev-table tbody tr').slice(0, rowsShown).show();
                $('#nav a:first').addClass('active');
                $('#nav a').bind('click', function () {

                    $('#nav a').removeClass('active');
                    $(this).addClass('active');
                    var currPage = $(this).attr('rel');
                    var startItem = currPage * rowsShown;
                    var endItem = startItem + rowsShown;
                    $('#dev-table tbody tr').css('opacity', '0.0').hide().slice(startItem, endItem).
                            css('display', 'block').animate({ opacity: 1 }, 300);
                });
            }
        });
    </script>
}

NET/TotalCoin/TotalCoin.Web/Views/Fanpage/Login.cshtml
@model TotalCoin.Web.Models.AdministrarFanpagesModel
@{
    ViewBag.Title = "ListarFanpages";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

@section Head{
    <script type="text/javascript">
        var appId = '@Microsoft.Azure.CloudConfigurationManager.GetSetting(TotalCoin.ConfigurationManager.ConfigurationNames.FacebookAppId)';

        window.fbAsyncInit = function () {
            FB.init({
                appId: appId,
                xfbml: true,
                version: 'v2.3'
            });
        };

        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) { return; }
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));

        var fbLogin = function () {
            FB.login(function (response) {
                if (response.status == 'connected') {
                    $("#accessToken")[0].value = response.authResponse.accessToken;
                    $("#signedRequest")[0].value = response.authResponse.signedRequest;
                    $("#userId")[0].value = response.authResponse.userID;
                    $("#nuevaTienda")[0].value = '@Model.NuevaTienda';
                    $("#fbForm").submit();
                } else {
                    $("#errorFb").show();
                }
            }, { scope: 'manage_pages', auth_type: 'reauthenticate' });
        };
    </script>

}

@section Body{

    @if (Model.NuevaTienda)
    {
        <section class="">
            <div class="container">
                <div class="row bs-wizard" style="border-bottom:0;">
                    <!--
                    ESTADOS DE LOS PASOS:
                     - active
                     - disable
                     - complete
                    -->

                    <div class="col-xs-4 bs-wizard-step complete">
                        <div class="text-center bs-wizard-stepnum">Cre&aacute; tu tienda</div>
                        <div class="progress"><div class="progress-bar"></div></div>
                        <a href="#" class="bs-wizard-dot"></a>
                    </div>

                    <div class="col-xs-4 bs-wizard-step complete">
                        <!-- complete -->
                        <div class="text-center bs-wizard-stepnum">Agreg&aacute; tus productos</div>
                        <div class="progress"><div class="progress-bar"></div></div>
                        <a href="#" class="bs-wizard-dot"></a>
                    </div>

                    <div class="col-xs-4 bs-wizard-step active">
                        <!-- complete -->
                        <div class="text-center bs-wizard-stepnum">Vincul&aacute; tu tienda</div>
                        <div class="progress"><div class="progress-bar"></div></div>
                        <a href="#" class="bs-wizard-dot"></a>
                    </div>
                </div>
            </div>
        </section> <!-- end our-work-container -->
    }
    <section>
        <div class="container">
            <div class="row" style="">
                <div class="col-sm-12">
                    <h1 class="Titulo">Integr&aacute; tu tienda con tus fanpages</h1>
                </div>
            </div>
            <div class="row" id="Conectar" style="">
                <div class="col-sm-12">
                    <p>Conectá tu cuenta de Facebook para vincular tu tienda a tus fanpages: </p>
                    @using (Html.BeginForm("Index", "Fanpage", FormMethod.Post, new { @id = "fbForm" }))
                    {
                        <input type="hidden" name="AccessToken" id="accessToken" />
                        <input type="hidden" name="SignedRequest" id="signedRequest" />
                        <input type="hidden" name="UserId" id="userId" />
                        <input type="hidden" name="NuevaTienda" id="nuevaTienda" />
                    }
                    <button onclick="fbLogin();" class="btn btn-facebook"><i class="fa fa-facebook"></i> | Conectar  mi cuenta de Facebook</button>
                </div>
            </div>
            <div class="row" style="display:none;" id="errorFb">
                <div class="col-sm-12">
                    <div class="alert alert-danger alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                        Debes permitirnos el acceso a la informaci&oacute;n sobre sus fanpages para poder vincular.
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top:40px">
                <div class="col-sm-12">
                    <a href="@(Model.NuevaTienda ? Url.Action("Index", "Producto") : Url.Action("Administrar", "Tienda"))" class="btn btn-default pull-left bot">VOLVER</a>
                </div>
            </div>
        </div>
    </section>
}