NET/TotalCoin/TotalCoin.Web/Controllers/TiendaController.cs
using Microsoft.Azure;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TotalCoin.ConfigurationManager;
using TotalCoin.Entidades;
using TotalCoin.ILogica;
using TotalCoin.Logica;
using TotalCoin.Web.Models;

namespace TotalCoin.Web.Controllers
{
    public class TiendaController : Controller
    {
        #region Fields

        private ITiendaLogica _tiendaLogica;
        private IFanpageLogica _fanpageLogica;
        private ICategoriaLogica _categoriaLogica;
        private IProductoLogica _productoLogica;

        #endregion Fields

        #region Constructores

        public TiendaController()
            : this(new TiendaLogica(), new FanpageLogica(), new ProductoLogica(), new CategoriaLogica())
        {
        }

        public TiendaController(ITiendaLogica tiendaLogica, IFanpageLogica fanpageLogica, IProductoLogica productoLogica, ICategoriaLogica categoriaLogica)
        {
            _tiendaLogica = tiendaLogica;
            _fanpageLogica = fanpageLogica;
            _productoLogica = productoLogica;
            _categoriaLogica = categoriaLogica;
        }

        #endregion Constructores

        #region Actions

        public ActionResult Index(string appKey, string email)
        {
            ViewBag.Email = email;
            ViewBag.AppKey = appKey;

            //El loader solo devuelve un loading, mientras se pide el AccessToken y obtiene los datos de la tienda
            return View("Loading");
        }

        public ActionResult WarmupEF() { 
            //Debido a tardanzas en EntityFramework al cargar por primera vez el modelo, se realizó este método que se ejecuta mientras está el loading.

            _tiendaLogica.WarmUpEF();
            return Json(new { success = true });
        }

        public ActionResult InitStore(string appKey, string email)
        {
            try
            {
                if (string.IsNullOrEmpty(appKey) && Session["AppKey"] != null)
                    appKey = Session["AppKey"].ToString();

                if (string.IsNullOrEmpty(email) && Session["Email"] != null)
                    email = Session["Email"].ToString();

                var tienda = _tiendaLogica.GetTienda(new Guid(appKey), email);

                Session["Email"] = email;
                Session["AppKey"] = appKey;

                if (tienda == null)
                    return View("Index");
                else
                {
                    Session["TiendaId"] = tienda.Id;
                    return RedirectToAction("Administrar");
                }
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }   
        }

        public ActionResult EditarTienda()
        {
            try
            {
                var model = new CrearTiendaModel();
                int tiendaId;

                if (Session["TiendaId"] != null && int.TryParse(Session["TiendaId"].ToString(), out tiendaId))
                {
                    model = ToModel(_tiendaLogica.GetById(tiendaId));
                    //Verifico si es el mismo email con el que intentó entrar. Por si estaba en una tienda, y después vio otra
                    if (Session["Email"] != null && Session["Email"].ToString() != model.Email) {
                        model = new CrearTiendaModel();
                    }
                }

                //Imagen default
                if(string.IsNullOrEmpty(model.ArchivoImagen))
                    model.ArchivoImagen  = "https://az653149.vo.msecnd.net/static/totalcoinstore/imagenes_tienda/tienda_default.png";
                
                //Get Merchants
                string email = Session["Email"].ToString();
                Guid apiKey = new Guid(Session["AppKey"].ToString());
                var merchants = _tiendaLogica.GetMerchants(apiKey, email);
                model.Merchants = ToModel(merchants).ToList();

                return View(model);
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }
        }

        public ActionResult Administrar(bool nombreEditado = false)
        {
            int tiendaId;

            if (Session["TiendaId"] != null && int.TryParse(Session["TiendaId"].ToString(), out tiendaId))
                return View(new AdministrarTiendaModel(tiendaId, false, nombreEditado));

            return RedirectToAction("StartStore");
        }

        public ActionResult GuardarTienda(CrearTiendaModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    string email = Session["Email"].ToString();
                    Guid apiKey = new Guid(Session["AppKey"].ToString());
                    var merchants = _tiendaLogica.GetMerchants(apiKey, email);
                    model.Merchants = ToModel(merchants).ToList();
                    return View("EditarTienda", model);
                }

                var rutaImagen = model.Imagen != null ? GuardarImagen(model.Imagen) : model.ArchivoImagen;

                var tienda = ToEntidad(model, rutaImagen);

                tienda = _tiendaLogica.Guardar(tienda);

                Session["TiendaId"] = tienda.Id;

                if (model.NuevaTienda)
                    return RedirectToAction("Index", "Producto", new { NuevaTienda = model.Id == null });
                else
                    return RedirectToAction("Administrar", new { nombreEditado = true });
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }
        }

        public ActionResult VerTienda()
        {
            try
            {
                ListarProductosModel model = new ListarProductosModel();
                Tienda tienda = new Tienda();

                var lPid = "";
                var appData = "";
                if (Request.Params["signed_request"] != null)
                {
                    string payload = Request.Params["signed_request"].Split('.')[1];
                    var encoding = new UTF8Encoding();
                    var decodedJson = payload.Replace("=", string.Empty).Replace('-', '+').Replace('_', '/');
                    var base64JsonArray = Convert.FromBase64String(decodedJson.PadRight(decodedJson.Length + (4 - decodedJson.Length % 4) % 4, '='));
                    var json = encoding.GetString(base64JsonArray);
                    var o = JObject.Parse(json);
                    lPid = Convert.ToString(o.SelectToken("page.id")).Replace("\"", "");
                    var lLiked = Convert.ToString(o.SelectToken("page.liked")).Replace("\"", "");
                    var lUserId = Convert.ToString(o.SelectToken("user_id")).Replace("\"", "");
                    appData = Convert.ToString(o.SelectToken("app_data")).Replace("\"", "");

                    tienda = _tiendaLogica.GetByFanpageId(lPid);
                    Session["TiendaIdDesdeFB"] = tienda.Id;
                    Session["page_id"] = lPid;
                }

                if (appData != "") {
                    var producto = _productoLogica.GetById(Convert.ToInt32(appData));
                    ProductoModel productoModel = ToModel(producto);
                    return View("../Producto/DetalleProducto", productoModel);
                }

                var productos = new List<Producto>();

                int tiendaId = tienda.Id;
                
                if (tienda.Id == 0)
                {
                    tiendaId = Convert.ToInt32(Session["TiendaIdDesdeFB"]);
                    lPid = Session["page_id"].ToString();
                }

                model.PageID = lPid;
                model.AppID = CloudConfigurationManager.GetSetting(ConfigurationNames.FacebookAppId);
                var cantProductos = 10;
                int.TryParse(CloudConfigurationManager.GetSetting(ConfigurationNames.CantidadDeProductosPorPagina), out cantProductos);
                model.Pagina = 1;
                model.CantPaginas = _productoLogica.GetCantidadDePaginas(tiendaId, cantProductos);
                productos = _productoLogica.GetPaginado(tiendaId, 1, cantProductos).ToList();

                foreach (Producto prod in productos)
                {
                    prod.Category.Subcategories = _categoriaLogica.GetAllSubcategorias(prod.Category.Id).ToList();
                }

                model.Productos = ToModel(productos);

                return View("ListadoProductos", model);
            }
            catch (Exception e)
            {
                return View("Error", "", e.Message);
            }
        }

        public ActionResult GetProductos(int? pagina, string busqueda, int? categoriaId) {
            try
            {
                var cantProductos = 10;
                int.TryParse(CloudConfigurationManager.GetSetting(ConfigurationNames.CantidadDeProductosPorPagina), out cantProductos); 
                if (Session["TiendaIdDesdeFB"] == null)
                    throw new ValidationException("Tienda invalida, por favor refresque la pagina.");

                var tiendaId = Convert.ToInt32(Session["TiendaIdDesdeFB"].ToString());

                if (!pagina.HasValue)
                    pagina = 1;
                
                var productos = ToModel(_productoLogica.GetPaginado(tiendaId, pagina.Value, cantProductos, busqueda, categoriaId));
                var cantPaginas = _productoLogica.GetCantidadDePaginas(tiendaId, cantProductos, busqueda, categoriaId);

                return Json(new { success = true, productos = productos, paginaActual = pagina.Value, cantidadPaginas = cantPaginas }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception e) {

NET/TotalCoin/TotalCoin.Web/Views/Shared/Loading.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TotalCoin</title>
    <style>
        div.Overlay {
            position: fixed;
            z-index: 99;
            top: 0px;
            left: 0px;
            background-color: #F1F1F1;
            width: 100%;
            height: 100%;
            filter: Alpha(Opacity=80);
            opacity: 0.8;
            -moz-opacity: 0.8;
        }
    </style>
</head>
<body>
    <div class="Overlay">
        <img src="https://az653149.vo.msecnd.net/static/assets/img/spinner-md.gif" style="position:fixed; top: 30%; left: 50%; margin-top: -64px; margin-left: -67px;" />
    </div>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/jquery-2.1.3.min.js")" type="text/javascript"></script>
    <script type="text/javascript">
    $(function () {
        $.ajax({
            type: "POST",
            url: '@Url.Action("WarmupEF", "Tienda")',
            data: { },
            success: function (data) {
                if (data.success)
                    window.location.replace('@Url.Action("InitStore", "Tienda")?appKey=@ViewBag.AppKey&email=@ViewBag.Email');
    }
    });
    });
</script>
</body>
</html>

NET/TotalCoin/TotalCoin.Web/Views/Shared/_FacebookLayoutPage.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Tienda TotalCoin</title>

        <!-- Bootstrap -->
        <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/bootstrap.min.css")" rel="stylesheet">
        <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/main.css")" rel="stylesheet">
        <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/dropdown.min.css")" rel="stylesheet">
        <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/semantic.css")" rel="stylesheet">
        <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/owl.carousel.css")" rel="stylesheet">
        <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/owl.theme.default.min.css")" rel="stylesheet">
        <link rel="stylesheet" href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/font-awesome.min.css")">
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600italic,600,700,700italic,900,900italic" rel="stylesheet" type="text/css">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        @RenderSection("Head", false)
    </head>
    <body class="fbapp" ng-app="TiendaTCFB">
        <!--<div id="fb-root"></div>-->
        <script>
            window.fbAsyncInit = function () {
                FB.init({
                    appId: '370604259802423',
                    xfbml: true,
                    version: 'v2.3'
                });
				 FB.Canvas.setAutoGrow(1000);
            };

            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) { return; }
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/es_LA/sdk.js";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
        @RenderSection("Body")

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/jquery-2.1.3.min.js")" type="text/javascript"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/bootstrap.min.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/semantic.min.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/dropdown.min.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/owl.carousel.min.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/jquery.zoom.min.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/angular.min.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/app.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/controllersFB.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/services2.js")"></script>
        <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/directivesFB.js")"></script>
        @RenderSection("Footer", false)
    </body>
</html>

NET/TotalCoin/TotalCoin.Web/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>@ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/bootstrap.min.css")" rel="stylesheet">
    <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/main.css")" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,200,200italic,300,300italic,400italic,600italic,600,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    <link href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/dropzone/dropzone.min.css")" rel="stylesheet">
    <link rel="stylesheet" href="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/css/font-awesome.min.css")">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
    </style>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/jquery-2.1.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/jquery-ui.js")" type="text/javascript"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/dropzone/dropzone.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/table.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/angular.min.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/app.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/controllers.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/directives.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/services2.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/angular-input-masks.min.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/underscore-min.js")"></script>
    <script src="@Url.Content("https://az653149.vo.msecnd.net/static/totalcoinstore/js/jquery.autonumeric.js")"></script>
    @RenderSection("Head", false)
</head>
<body ng-app="TiendaTC">

    @RenderSection("Body")
</body>
</html>